### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by philouc** [CosmoStat/Sparse2D#1]
My laptop: Ubuntu release 16.04 LTS
I followed the instructions for installing sparse2D and I got the following error message because the build directory was existing before the configuration step.
  pc174679@is231880:/volatile/ciuciu/work/code/Sparse2D$ mkdir build
mkdir: impossible de créer le répertoire «build»: Le fichier existe

Next of course the call to cmake failed too:
pc174679@is231880:/volatile/ciuciu/work/code/Sparse2D/build$ cmake ..
CMake Error: The current CMakeCache.txt directory /volatile/ciuciu/work/code/Sparse2D/build/CMakeCache.txt is different than the directory /Users/sfarrens/Dropbox/CEA/P-ISAP/isap/cxx/sparse2d_opt_w_unit/build2 where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
CMake Error: The source "/volatile/ciuciu/work/code/Sparse2D/CMakeLists.txt" does not match the source "/Users/sfarrens/Dropbox/CEA/P-ISAP/isap/cxx/sparse2d_opt_w_unit/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.

**My solution to that was to remove the build directory and relaunch the procedure. Now it works!**

**Comment by sfarrens** [comment]
The build files have been removed from the repository.
