### ISSUE TITLE
msvst_2d1d build with recent compiler

### ISSUE THREAD

**Issue by tstolarczyk** [CosmoStat/Sparse2D#13]
Facing difficulties to compile the ISAP official (from the ISAP web site) msvst_2d1d with gcc 7 on MacOsX, 
it is suggested to merge msvst_2d1d with sparse2d that is being upgraded since it already handles most of the msvst_2d1d required modules.

**Comment by sfarrens** [comment]
MSVST can now be built with Sparse2D using the option `BUILD_MSVST=ON`. e.g.

```bash
$ cd build
$ cmake .. -DBUILD_MSVST=ON
```
