### ISSUE TITLE
Static mr_filter and mr_transform

### ISSUE THREAD

**Issue by jjlk** [CosmoStat/Sparse2D#17]
Hi @sfarrens ,
I'm working at DAp in the Cherenkov Telescope Array (CTA) group and I'd like to know if there are any options to compile sparse2d with cmake in order to get static programs for mr_filter and mr_transform.

Indeed I'm working on clusters with servers having the same architecture but they don't know about all the librairies at the compilation time (e.g. cfitsio). Do you know if there are any ways do statically link the programs (I'm not really familiar with the cmake utilities)?

Thanks in advance

**Comment by sfarrens** [comment]
Hi @jjlk, I think I can add an option to build static libs, but I need to look into it. I will get back to you soon. :)

**Comment by jjlk** [comment]
Great, thanks!

**Comment by sfarrens** [comment]
I have opened a PR (#18) with the cmake option `-DBUILD_STATIC`. You can checkout the PR as follows:

```bash
git fetch origin pull/18/head:static_build
git checkout static_build
```

If this works I can merge the PR.
