### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by philouc** [CosmoStat/Sparse2D#2]
I launched the compilation:
**pc174679@is231880:/volatile/ciuciu/work/code/Sparse2D/build$ make**
and it fails on the target **cur_contrast**  (see below)

[ 86%] Linking CXX executable cur_contrast
libtools.a(IM_IO.cc.o) : Dans la fonction « io_read_ima_int(char*, to_array<int, false>&, fitsstruct*, Bool) » :
IM_IO.cc:(.text+0x832) : référence indéfinie vers « io_disp::read_ima_int(char*, to_array<int, false>&) »
libtools.a(IM_IO.cc.o) : Dans la fonction « io_write_ima_int(char*, to_array<int, false>&, fitsstruct*) » :
IM_IO.cc:(.text+0xaa6) : référence indéfinie vers « io_disp::write_ima_int(char*, to_array<int, false>&) »
libtools.a(IM_IO.cc.o) : Dans la fonction « io_read_ima_float(char*, to_array<float, false>&, fitsstruct*) » :
IM_IO.cc:(.text+0xde4) : référence indéfinie vers « io_disp::read_ima_float(char*, to_array<float, false>&) »
libtools.a(IM_IO.cc.o) : Dans la fonction « io_write_ima_float(char*, to_array<float, false>&, fitsstruct*, Bool) » :
IM_IO.cc:(.text+0x105b) : référence indéfinie vers « io_disp::write_ima_float(char*, to_array<float, false>&) »
libtools.a(IM_IO.cc.o) : Dans la fonction « io_read_ima_complex_f(char*, to_array<std::complex<float>, false>&) » :
IM_IO.cc:(.text+0x16f3) : référence indéfinie vers « io_disp::read_ima_complex_f(char*, to_array<std::complex<float>, false>&) »
libtools.a(IM_IO.cc.o) : Dans la fonction « io_write_ima_complex_f(char*, to_array<std::complex<float>, false>&) » :
IM_IO.cc:(.text+0x17fb) : référence indéfinie vers « io_disp::write_ima_complex_f(char*, to_array<std::complex<float>, false>&) »
libtools.a(IM_IO.cc.o) : Dans la fonction « io_disp::io_disp() » :
IM_IO.cc:(.text._ZN7io_dispC1Ev[_ZN7io_dispC1Ev]+0x1d) : référence indéfinie vers « vtable for io_disp »
IM_IO.cc:(.text._ZN7io_dispC1Ev[_ZN7io_dispC1Ev]+0x35) : référence indéfinie vers « vtable for io_disp »
libtools.a(IM_IO.cc.o) : Dans la fonction « io_disp::~io_disp() » :
IM_IO.cc:(.text._ZN7io_dispD1Ev[_ZN7io_dispD1Ev]+0xd) : référence indéfinie vers « vtable for io_disp »
IM_IO.cc:(.text._ZN7io_dispD1Ev[_ZN7io_dispD1Ev]+0x25) : référence indéfinie vers « vtable for io_disp »
collect2: error: ld returned 1 exit status
CMakeFiles/cur_contrast.dir/build.make:98 : la recette pour la cible « cur_contrast » a échouée
make[2]: *** [cur_contrast] Erreur 1
CMakeFiles/Makefile2:70 : la recette pour la cible « CMakeFiles/cur_contrast.dir/all » a échouée
make[1]: *** [CMakeFiles/cur_contrast.dir/all] Erreur 2
Makefile:138 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2

**Comment by sfarrens** [comment]
Please pull the latest updates and try again.
