### ISSUE TITLE
binary_function not anymore supported

### ISSUE THREAD

**Issue by jstarck** [CosmoStat/Sparse2D#51]
binary_function used in WPackets.h is a not supported by the compiler anymore.

**Comment by arnablahiry** [comment]
I am facing this problem when trying to install the CosmoStat package. I believe this is in the Sparse2D package installation? I tried to install the Sparse2D package separately as well (both using homebrew and manually) and it is showing a similar problem with binary_function. I am attaching the log file for when I tried to install Sparse2D separately using homebrew (filename: 03.make renamed to sparse2d log 3.txt) for reference. Has there been any resolution in this regard?
[sparse2d log 3.txt](https://github.com/CosmoStat/Sparse2D/files/14823548/sparse2d.log.3.txt)

**Comment by sfarrens** [comment]
@arnablahiry are you trying to build on Apple Silicon (e.g. M1/M2)? I just tested the current master branch on an Intel Mac and everything was built without any issues.

**Comment by arnablahiry** [comment]
@sfarrens yes my machine is apple silicon, with the M3 chip. i think it is unable to build in this one?

**Comment by sfarrens** [comment]
Was resolved in #52
